### ISSUE TITLE
BUG: GUI Scaling

### ISSUE THREAD

**Issue by EdTheLoon** [Sycosys/Sailwind-Map#7]
GUI scaling is off by quite a bit. 
I recommend using percentages in the CSS for element sizes.

![GUI Scaling](https://user-images.githubusercontent.com/911746/147590582-cca03f89-1fa4-4305-8fef-8ecc95593014.png)

**Comment by Sycosys** [comment]
your changes broke it on android. reverted.  What browser are you using?
also i did my dev at 4k and 1080p

**Comment by EdTheLoon** [comment]
Ah damn. I didn't test on Android. I'm using firefox. I'll look into it. I didn't use features that aren't supported on major browsers so it will be a nitpicky little detail somewhere.

**Comment by EdTheLoon** [comment]
> your changes broke it on android. 

Can you specify what was wrong?

**Comment by EdTheLoon** [comment]
Okay. I have done a major re-work to the underlying CSS and HTML structure. 
I've tested on Windows (Firefox 1080p) and Google Pixel Pro 6 (Chrome and Firefox, 1440 x 3120)

All GUI elements should now scale properly. Including buttons, inputs, labels, form popup, compass.

You can check my live version here:
[Live Test Website](https://reids.scot/swm/)

**Comment by EdTheLoon** [comment]
#9 Resolved.
